- name: Default git branch
  git_config:
    name: init.defaultBranch
    value: main
    scope: global

- name: Default git editor
  git_config:
    name: core.editor
    value: vim
    scope: global

- name: My committer email
  git_config:
    name: user.email
    value: p@tricklynch.org
    scope: global

- name: My name
  git_config:
    name: user.name
    value: Patrick Lynch
    scope: global

- name: Get vimrc
  get_url:
    url: https://raw.githubusercontent.com/amix/vimrc/master/vimrcs/basic.vim
    dest: ~/.vimrc
    mode: 0600

- name: Set fish as default shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/fish
  become: True
