- name: Default git branch
  git_config:
    name: init.defaultBranch
    value: main
    scope: global

- name: Default git editor
  git_config:
    name: core.editor
    value: vim
    scope: global

- name: My committer email
  git_config:
    name: user.email
    value: p@tricklynch.org
    scope: global

- name: My name
  git_config:
    name: user.name
    value: Patrick Lynch
    scope: global

- name: Set commit signing key
  git_config:
    name: user.signingkey
    value: CD942B9EF7D9247C
    scope: global

- name: Sign all commits
  git_config:
    name: commit.gpgsign
    value: true
    scope: global

- name: Get vimrc
  get_url:
    url: https://raw.githubusercontent.com/amix/vimrc/master/vimrcs/basic.vim
    dest: ~/.vimrc
    mode: 0600

- name: Set fish as default shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/fish
  become: true

- name: Does Terminator config dir exist
  stat:
    path: ~/.config/terminator
  register: terminator_conf_dir

- name: Make Terminator config directory
  file:
    path: ~/.config/terminator
    state: directory
    mode: 0700
  when: not terminator_conf_dir.stat.exists

- name: Configure Terminator
  copy:
    src: "{{ role_path }}/files/terminator.conf"
    dest: ~/.config/terminator/config
    mode: 0600
