- name: Install from dnf
  dnf: name={{ item }}
  loop:
    - asciinema
    - cloc
    - cowsay
    - fish
    - fortune-mod
    - keepassxc
    - lolcat
    - snapd
    - terminator
    - xclip
  become: true

- name: Configure snap
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
  become: true

- name: Install from snap
  snap: name={{ item }}
  loop:
    - authy
    - bitwarden
    - discord
    - signal-desktop
  become: true

- name: Install from snap with classic
  snap:
    name: "{{ item }}"
    classic: true
  loop:
    - code
  become: true

- name: Install from homebrew
  homebrew: name={{ item }}
  loop:
    - dog
    - git
    - htop
    - python3
    - vim

- name: Install from homebrew build from source
  homebrew:
    name={{ item }}
    install_options=build-from-source
  loop:
    - gping

- name: Are fonts installed
  stat:
    path: ~/.local/share/fonts/NerdFonts
  register: fonts

- name: Retrieve fonts
  git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    dest: /tmp/nerd-fonts
    clone: true
    depth: 1
    version: c98cb457d45ad71866c6e51aa6a57e9123d3d7cf
  when: not fonts.stat.exists

- name: Install fonts
  command: /tmp/nerd-fonts/install.sh
  when: not fonts.stat.exists

- name: Is omf installed
  stat:
    path: ~/.local/share/omf
  register: omf

- name: Get omf installer
  get_url:
    url: https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install
    checksum: "sha256:https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install.sha256"
    dest: /tmp/omfinstall.fish
    mode: 500
  when: not omf.stat.exists

- name: Install omf
  command: fish /tmp/omfinstall.fish --noninteractive --yes
  when: not omf.stat.exists

- name: Is bobthefish installed
  stat:
    path: ~/.local/share/omf/themes/bobthefish
  register: bobthefish

- name: Install bobthefish
  command: fish -c "omf install bobthefish"
  when: not bobthefish.stat.exists

- name: Install system python packages
  pip: name={{ item }}
  loop:
    - ansible-lint
    - pre-commit
