- name: Add RPM Fusion Free key
  rpm_key:
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
    state: present
  become: true

- name: Add RPM Fusion Nonfree key
  rpm_key:
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
    state: present
  become: true

- name: Add Vivaldi key
  rpm_key:
    key: https://repo.vivaldi.com/stable/linux_signing_key.pub
    state: present
  become: true

- name: Enable RPM Fusion (free)
  dnf:
    name: https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
  become: true

- name: Enable RPM Fusion (nonfree)
  dnf:
    name: https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
  become: true

- name: Enable Vivaldi repo
  yum_repository:
    baseurl: https://repo.vivaldi.com/archive/rpm/x86_64
    name: vivaldi
    description: Repo for Vivaldi browser
    state: present
  become: true

- name: Install from dnf
  dnf: name={{ item }}
  loop:
    - asciinema
    - cloc
    - cowsay
    - ffmpeg-libs
    - fish
    - fortune-mod
    - graphviz
    - keepassxc
    - lolcat
    - mpv
    - nodejs
    - snapd
    - steam
    - terminator
    - vivaldi-stable
    - xclip
  become: true

- name: Configure snap
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
  become: true

- name: Install from snap
  snap: name={{ item }}
  loop:
    - authy
    - bitwarden
    - discord
    - mdless
    - signal-desktop
  become: true

- name: Install from snap with classic
  snap:
    name: "{{ item }}"
    classic: true
  loop:
    - code
  become: true

- name: Install from homebrew
  homebrew: name={{ item }}
  loop:
    - dog
    - git
    - htop
    - python3
    - vim

- name: Install from homebrew build from source
  homebrew:
    name={{ item }}
    install_options=build-from-source
  loop:
    - gping

- name: Are fonts installed
  stat:
    path: ~/.local/share/fonts/NerdFonts
  register: fonts

- name: Retrieve fonts
  git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    dest: /tmp/nerd-fonts
    depth: 1
    version: c98cb457d45ad71866c6e51aa6a57e9123d3d7cf
  when: not fonts.stat.exists

- name: Install fonts
  command: /tmp/nerd-fonts/install.sh
  when: not fonts.stat.exists

- name: Is omf installed
  stat:
    path: ~/.local/share/omf
  register: omf

- name: Get omf installer
  get_url:
    url: https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install
    checksum: "sha256:https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install.sha256"
    dest: /tmp/omfinstall.fish
    mode: 500
  when: not omf.stat.exists

- name: Install omf
  command: fish /tmp/omfinstall.fish --noninteractive --yes
  when: not omf.stat.exists

- name: Is bobthefish installed
  stat:
    path: ~/.local/share/omf/themes/bobthefish
  register: bobthefish

- name: Install bobthefish
  command: fish -c "omf install bobthefish"
  when: not bobthefish.stat.exists

- name: Install system python packages
  pip: name={{ item }}
  loop:
    - ansible-lint
    - pre-commit

- name: Is spongebob-cli downloaded
  stat:
    path: ~/Documents/spongebob-cli
  register: sbcli_downloaded

- name: Clone spongebob-cli
  git:
    repo: https://github.com/trakBan/spongebob-cli
    dest: ~/Documents/spongebob-cli
    depth: 1
    version: eac7eded094a483495ac855cebadf1e168ee5b78
  when: not sbcli_downloaded.stat.exists

- name: Is spongebob-cli installed
  command: which spongebob-cli
  register: sbcli_installed
  failed_when: false
  when: true

- name: Make spongebob-cli executable
  file:
    path: ~/Documents/spongebob-cli/spongebob-cli
    mode: 0500
  when: sbcli_installed.rc != 0

- name: Install spongebob-cli
  command: python setup.py install --user
  args:
    chdir: ~/Documents/spongebob-cli
  when: sbcli_installed.rc != 0
