- name: Install from dnf
  dnf: name={{ item }}
  with_items:
    - cloc
    - cowsay
    - fortune-mod
    - keepassxc
    - kitty
    - lolcat
    - snapd
  become: True

- name: Configure snap
  ansible.builtin.file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
  become: True

- name: Install from snap
  snap: name={{ item }}
  with_items:
    - bitwarden
    - discord
    - signal-desktop
  become: True

- name: Install from snap with classic
  snap:
    name: "{{ item }}"
    classic: True
  with_items:
    - code
  become: True

- name: Add keepassxc favorite
  copy:
    src: "{{ role_path }}/files/KeePassXC.desktop"
    dest: /usr/share/applications/KeePassXC.desktop
