- name: Ensure anticipated tools are installed on $PATH
  command: "which {{ item }}"
  loop:
    - ansible-playbook
    - ansible-lint
    - asciinema
    - authy
    - bitwarden
    - brew
    - cloc
    - code
    - cowsay
    - discord
    - dog
    - dnf
    - fish
    - fortune
    - git
    - gping
    - gpg
    - grep
    - htop
    - keepassxc
    - lolcat
    - mdless
    - pip
    - pre-commit
    - python
    - signal-desktop
    - snap
    - terminator
    - vim
    - xclip
  when: true

- name: Ensure fish is default shell
  shell: "set -euo pipefail && userdbctl | grep {{ ansible_user_id }}"
  register: default_shell_result
  failed_when: '"fish" not in default_shell_result.stdout'
  when: true
